# Generated by Django 2.1.3 on 2018-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='asdasdasd', editable=False, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='template_file',
            field=models.CharField(default='asdasd', max_length=100),
            preserve_default=False,
        ),
    ]
