# Generated by Django 2.1.3 on 2018-12-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0003_auto_20181220_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemicon',
            name='icon_type',
            field=models.CharField(choices=[('svg', 'SVG Code'), ('img', 'Image file')], default='svg', max_length=3),
            preserve_default=False,
        ),
    ]
