# Generated by Django 2.1.3 on 2018-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0004_itemicon_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemguide',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemtwocolumn',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
