# Generated by Django 2.1.3 on 2018-12-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0006_itemlist_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemicon',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distinct_pages.Page'),
        ),
    ]
