# Generated by Django 2.1.3 on 2018-12-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0007_itemicon_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemicon',
            name='page',
        ),
    ]
