# Generated by Django 2.1.3 on 2018-12-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0008_remove_itemicon_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemguide',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distinct_pages.Page'),
        ),
        migrations.AddField(
            model_name='itemtwocolumn',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distinct_pages.Page'),
        ),
    ]
