# Generated by Django 2.1.3 on 2019-01-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0011_auto_20190102_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemguide',
            name='page',
        ),
    ]
