# Generated by Django 2.1.3 on 2019-01-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distinct_pages', '0012_remove_itemguide_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemguide',
            name='small_desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Small Description'),
        ),
        migrations.AddField(
            model_name='itemguide',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
