# Generated by Django 2.1.3 on 2018-12-10 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import writing.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Blog Category Relation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', djrichtextfield.models.RichTextField()),
                ('slug', models.SlugField(allow_unicode=True, editable=False, unique=True)),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished'), ('a', 'Archived')], default='u', max_length=1)),
                ('feature_img', models.ImageField(blank=True, null=True, upload_to=writing.utils.get_image_path, verbose_name='Feature Image')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writing.Post')),
                ('post_type', models.CharField(default='a', editable=False, max_length=1)),
            ],
            bases=('writing.post',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writing.Post')),
                ('post_type', models.CharField(default='b', editable=False, max_length=1)),
            ],
            bases=('writing.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.Section'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.Profile'),
        ),
        migrations.AddField(
            model_name='categorize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(through='writing.Categorize', to='writing.Blog'),
        ),
        migrations.AddField(
            model_name='categorize',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Blog'),
        ),
    ]
