# Generated by Django 2.1.3 on 2018-12-06 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import writing.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Post Category Relation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('a', 'Article'), ('b', 'Blog')], max_length=1)),
                ('title', models.CharField(max_length=200)),
                ('content', djrichtextfield.models.RichTextField()),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
                ('status', models.CharField(choices=[('p', 'Published'), ('u', 'Unpublished'), ('a', 'Archived')], default='u', max_length=1)),
                ('feature_img', models.ImageField(blank=True, null=True, upload_to=writing.utils.get_image_path, verbose_name='Feature Image')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=1000)),
                ('icon', models.TextField()),
                ('slug', models.SlugField(allow_unicode=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sectionize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Post')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Section')),
            ],
            options={
                'verbose_name': 'Section Category Relation',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='section',
            name='post',
            field=models.ManyToManyField(through='writing.Sectionize', to='writing.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.Profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(through='writing.Categorize', to='writing.Post'),
        ),
        migrations.AddField(
            model_name='categorize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Category'),
        ),
        migrations.AddField(
            model_name='categorize',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Post'),
        ),
    ]
