# Generated by Django 2.1.3 on 2018-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20181206_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, unique=True),
        ),
    ]
