# Generated by Django 2.1.3 on 2018-12-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20181206_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionize',
            name='post',
        ),
        migrations.RemoveField(
            model_name='sectionize',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.Section'),
        ),
        migrations.DeleteModel(
            name='Sectionize',
        ),
    ]
