# Generated by Django 2.1.3 on 2018-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_auto_20181210_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='post_type',
            field=models.CharField(choices=[('a', 'Article'), ('b', 'Blog')], default='b', max_length=1),
            preserve_default=False,
        ),
    ]
