# Generated by Django 2.1.3 on 2018-12-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_auto_20181210_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
    ]
