# Generated by Django 2.1.3 on 2018-12-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0005_section_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, limit_choices_to={'post_type': 'a'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.Section'),
        ),
        migrations.AddField(
            model_name='blog',
            name='section',
            field=models.ForeignKey(blank=True, limit_choices_to={'post_type': 'b'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='writing.Section'),
        ),
    ]
