# Generated by Django 2.1.3 on 2018-12-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_page_create_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
