# Generated by Django 2.1.3 on 2019-01-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('url_text', models.CharField(max_length=300)),
                ('position', models.CharField(choices=[('top', 'Header'), ('btm', 'Footer')], max_length=3)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Menu')),
            ],
        ),
    ]
