# Generated by Django 2.1.3 on 2019-01-16 10:28

import dashboard.utils
import django.contrib.postgres.fields
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_img', models.ImageField(upload_to=dashboard.utils.get_image_path, verbose_name='Top Image')),
                ('top_text', djrichtextfield.models.RichTextField()),
                ('service_heading', models.CharField(max_length=300, verbose_name='Service Heading')),
                ('service_sub_heading', models.CharField(max_length=300, verbose_name='Service Sub Heading')),
                ('service_items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=2), size=None)),
                ('service_img', models.ImageField(upload_to=dashboard.utils.get_image_path, verbose_name='Service Image')),
                ('statistics', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=2), size=None)),
                ('review_heading', models.CharField(max_length=500)),
                ('review_items', django.contrib.postgres.fields.ArrayField(base_field=djrichtextfield.models.RichTextField(), size=2)),
                ('review_bg', models.ImageField(upload_to=dashboard.utils.get_image_path, verbose_name='Review Background Image')),
                ('faq_heading', models.CharField(max_length=300)),
                ('faq_img', models.ImageField(upload_to=dashboard.utils.get_image_path, verbose_name='FAQ Image')),
                ('faqs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), size=None), size=None)),
                ('quote_heading', models.CharField(max_length=300)),
                ('quote_bg', models.ImageField(upload_to=dashboard.utils.get_image_path, verbose_name='Get Quote Background Image')),
                ('footer_left', models.TextField()),
                ('footer_middle', models.TextField()),
                ('copyright_text', models.CharField(max_length=200)),
                ('social_links', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=2), size=None)),
            ],
        ),
    ]
