# Generated by Django 2.1.3 on 2019-01-16 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_generaltopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltopic',
            name='last_edited_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last edited on'),
            preserve_default=False,
        ),
    ]
