# Generated by Django 2.1.3 on 2019-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_generaltopic_last_edited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltopic',
            name='last_edited_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last edited on'),
        ),
    ]
