# Generated by Django 2.1.3 on 2019-01-19 00:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190117_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltopic',
            name='social_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=2), size=None),
        ),
    ]
