# Generated by Django 2.1.3 on 2019-01-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190119_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltopic',
            name='top_quote_heading',
            field=models.CharField(default='Find Affordable Health quotesTh that right for you', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltopic',
            name='top_quote_sub_heading',
            field=models.CharField(default='Instantly Compare Over 4,000 Insurance Plans', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaltopic',
            name='quote_heading',
            field=models.CharField(max_length=300, verbose_name='All page quote Heading'),
        ),
    ]
