# Generated by Django 2.1.3 on 2019-01-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190120_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltopic',
            name='service_items',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generaltopic',
            name='statistics',
            field=models.TextField(),
        ),
    ]
