# Generated by Django 2.1.3 on 2019-01-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190120_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaltopic',
            name='review_items',
        ),
    ]
