# Generated by Django 2.1.3 on 2019-01-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_generaltopic_review_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltopic',
            name='review_items',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
