# Generated by Django 2.1.3 on 2019-01-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_generaltopic_review_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaltopic',
            name='faqs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generaltopic',
            name='social_links',
            field=models.TextField(),
        ),
    ]
