# Generated by Django 2.1.3 on 2019-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190120_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltopic',
            name='meta_tags',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltopic',
            name='site_main_title',
            field=models.CharField(default='asd', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaltopic',
            name='site_name',
            field=models.CharField(default='asd', max_length=250),
            preserve_default=False,
        ),
    ]
