# Generated by Django 2.1.3 on 2019-01-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190130_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaltopic',
            old_name='meta_tags',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='generaltopic',
            name='meta_keywords',
            field=models.TextField(default='Asd'),
            preserve_default=False,
        ),
    ]
