#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
DBNAME="qturbo"
DBUSER="qturbo"
DBPASS="qturbo"


OS="$(uname -s)"

if [ $OS == "Darwin" ]; then
    dropdb $DBNAME
else
sudo -u postgres bash << EOF
    echo "DB User Password: $DBPASS"
    dropdb -U $DBUSER -W $DBNAME
EOF
fi
