# Generated by Django 2.1.3 on 2018-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
