# Generated by Django 2.1.3 on 2018-12-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stmenroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeshieldStm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimm_enroll_id', models.CharField(max_length=20)),
                ('Plan_ID', models.TextField()),
                ('Name', models.TextField()),
                ('plan_name_for_img', models.TextField()),
                ('month', models.TextField()),
                ('plan_name', models.TextField()),
                ('unique_url', models.TextField()),
                ('Premium', models.DecimalField(decimal_places=2, max_digits=20)),
                ('actual_premium', models.DecimalField(decimal_places=2, max_digits=20)),
                ('option', models.TextField()),
                ('Coinsurance_Percentage', models.TextField()),
                ('out_of_pocket_value', models.TextField()),
                ('coverage_max_value', models.TextField()),
                ('Duration_Coverage', models.TextField()),
                ('Deductible_Option', models.TextField()),
                ('quote_request_timestamp', models.IntegerField()),
                ('copay', models.TextField()),
                ('copay_text', models.TextField()),
                ('Quote_ID', models.TextField()),
                ('Access_Token', models.TextField()),
                ('Plan', models.TextField()),
                ('Plan_Name', models.TextField(db_column='everest_plan_name')),
                ('Coinsurance_Limit', models.TextField()),
                ('ChoiceValueSavings_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ChoiceValue_AdminFee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RealValueSavings_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RealValueSavings_AdminFee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('VBP_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('EnrollmentFee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TelaDoc_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Medsense_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RxAdvocacy_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Enrollment_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Payment_Option', models.TextField()),
                ('Coverage_Max', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Benefit_Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('copay_2', models.TextField()),
                ('copay_2_text', models.TextField()),
                ('stm_enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.StmEnroll', verbose_name='Enroll')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
