# Generated by Django 2.1.3 on 2018-12-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_lifeshieldstm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimm_enroll_id', models.CharField(max_length=20)),
                ('Relation', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child')], max_length=50)),
                ('First_Name', models.TextField()),
                ('Middle_Name', models.TextField(blank=True, null=True)),
                ('Last_Name', models.TextField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Feet', models.IntegerField(blank=True, null=True)),
                ('Inch', models.IntegerField(blank=True, null=True)),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('SSN', models.TextField(blank=True, null=True)),
                ('stm_enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.StmEnroll', verbose_name='Enroll')),
            ],
        ),
    ]
