# Generated by Django 2.1.3 on 2018-12-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_dependent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimm_enroll_id', models.CharField(max_length=20)),
                ('stm_name', models.CharField(choices=[('Everest STM', 'Everest STM'), ('LifeShield STM', 'LifeShield STM'), ('HealtheFlex STM', 'HealtheFlex STM'), ('HealtheMed STM', 'HealtheMed STM'), ('Premier STM', 'Premier STM'), ('Sage STM', 'Sage STM'), ('Principle Advantage', 'Principle Advantage')], max_length=100, verbose_name='Main Plan')),
                ('addon_id', models.IntegerField()),
                ('Name', models.TextField()),
                ('carrier_name', models.TextField(blank=True, null=True)),
                ('carrier_id', models.TextField(blank=True, null=True)),
                ('Premium', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Premium')),
                ('actual_premium', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Actual Premium')),
                ('AdministrativeFee', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Administrative Fee')),
                ('EnrollmentFee', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Enrollment Fee')),
                ('MedsenseFee', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Medsense Fee')),
                ('Embeded', models.CharField(max_length=100)),
                ('Plan', models.CharField(blank=True, max_length=100, null=True)),
                ('Plan_Code', models.CharField(blank=True, max_length=100, null=True)),
                ('Deductible', models.CharField(blank=True, max_length=100, null=True)),
                ('Member_ID', models.CharField(blank=True, max_length=500, null=True)),
                ('stm_enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.StmEnroll', verbose_name='Enroll')),
            ],
        ),
    ]
