# Generated by Django 2.1.3 on 2018-12-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_healthchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandAloneAddonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimm_enroll_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('Plan_ID', models.CharField(db_index=True, max_length=600, verbose_name='Plan ID')),
                ('Plan_Type', models.CharField(choices=[('Single Member', 'Single Member'), ('Member+1', 'Member+1'), ('Family', 'Family')], max_length=500)),
                ('Name', models.CharField(db_index=True, max_length=600)),
                ('Lim_Plan_Name', models.CharField(db_index=True, max_length=200)),
                ('plan_name_for_img', models.CharField(db_index=True, max_length=600)),
                ('plan_name', models.CharField(blank=True, max_length=600, null=True)),
                ('unique_url', models.CharField(blank=True, db_index=True, max_length=700, null=True)),
                ('Premium', models.DecimalField(decimal_places=2, max_digits=20)),
                ('EnrollmentFee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Enrollment_Fee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Administrative_Fee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('AdministrativeFee', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('actual_premium', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Quote_ID', models.CharField(blank=True, max_length=600, null=True)),
                ('Access_Token', models.CharField(blank=True, max_length=700, null=True)),
                ('quote_request_timestamp', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('stm_enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.StmEnroll', verbose_name='Enroll')),
            ],
            options={
                'db_table': 'stand_alone_addon_plan',
            },
        ),
    ]
