# Generated by Django 2.1.3 on 2018-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_standaloneaddonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmenroll',
            name='Applicant_is_Child',
            field=models.BooleanField(default=False),
        ),
    ]
