# Generated by Django 2.1.3 on 2018-12-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_carrier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='leads',
            old_name='zip_code',
            new_name='Zip_Code',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='gender',
        ),
        migrations.AddField(
            model_name='leads',
            name='Gender',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='quote_store_key',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leads',
            name='stm_enroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.StmEnroll', verbose_name='Enroll'),
        ),
        migrations.AddField(
            model_name='leads',
            name='vimm_enroll_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
