# Generated by Django 2.1.3 on 2018-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_dependent_tobacco'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmenroll',
            name='Tobacco',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='Tobacco',
            field=models.TextField(blank=True, max_length=1, null=True),
        ),
    ]
