# Generated by Django 2.1.3 on 2019-01-23 10:24

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_auto_20190107_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', djrichtextfield.models.RichTextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitsAndCoverage',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quotes.Feature')),
                ('feature_type', models.CharField(default='Benefits and Coverage', max_length=50)),
                ('self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.BenefitsAndCoverage')),
            ],
            bases=('quotes.feature',),
        ),
        migrations.CreateModel(
            name='RestrictionsAndOmissions',
            fields=[
                ('feature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quotes.Feature')),
                ('feature_type', models.CharField(default='Restrictions and Omissions', max_length=50)),
                ('self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.RestrictionsAndOmissions')),
            ],
            bases=('quotes.feature',),
        ),
        migrations.AddField(
            model_name='feature',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.Carrier'),
        ),
    ]
