# Generated by Django 2.1.3 on 2019-01-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_auto_20190123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.Carrier'),
            preserve_default=False,
        ),
    ]
