# Generated by Django 2.1.3 on 2019-01-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0021_benefitsandcoverage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsandcoverage',
            name='feature_type',
            field=models.CharField(default='Benefits and Coverage', editable=False, max_length=50),
        ),
    ]
