# Generated by Django 2.1.3 on 2019-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0022_auto_20190129_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanthealthstm',
            name='general_url',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifeshieldstm',
            name='general_url',
            field=models.TextField(default='/asd/asda/sd'),
            preserve_default=False,
        ),
    ]
