# Generated by Django 2.1.3 on 2019-02-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_auto_20190130_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanthealthstm',
            name='general_plan_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifeshieldstm',
            name='general_plan_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
