# Generated by Django 2.1.3 on 2019-02-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0024_auto_20190202_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stmenroll',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='CellPhone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='City',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='DayPhone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='First_Name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='IP_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Mailing_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Mailing_City',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Mailing_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Mailing_State',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Mailing_ZipCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stmenroll',
            name='Name_Auth',
            field=models.TextField(blank=True, null=True),
        ),
    ]
