# Generated by Django 2.1.3 on 2019-02-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_auto_20190224_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='First_Name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='Last_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
