# Generated by Django 2.1.3 on 2019-02-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_mainplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainplan',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
