# Generated by Django 2.1.3 on 2019-02-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_mainplan_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalacare',
            name='stm_enroll',
        ),
        migrations.DeleteModel(
            name='VitalaCare',
        ),
    ]
