# Generated by Django 2.1.3 on 2019-02-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_auto_20190211_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeshieldstm',
            name='stm_enroll',
        ),
        migrations.DeleteModel(
            name='LifeshieldStm',
        ),
    ]
