# Generated by Django 2.1.3 on 2019-02-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0030_auto_20190211_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthchoice',
            name='stm_enroll',
        ),
        migrations.DeleteModel(
            name='HealthChoice',
        ),
    ]
