# Generated by Django 2.1.3 on 2019-02-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0031_auto_20190211_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legionlimitedmedical',
            name='stm_enroll',
        ),
        migrations.RemoveField(
            model_name='standaloneaddonplan',
            name='stm_enroll',
        ),
        migrations.DeleteModel(
            name='LegionLimitedMedical',
        ),
        migrations.DeleteModel(
            name='StandAloneAddonPlan',
        ),
    ]
