# Generated by Django 2.1.3 on 2019-03-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0032_auto_20190212_0410'),
        ('quotes', '0026_auto_20190224_1139'),
    ]

    operations = [
    ]
