# Generated by Django 2.1.3 on 2019-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0033_merge_20190303_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefitsandcoverage',
            old_name='self',
            new_name='self_fk',
        ),
        migrations.RenameField(
            model_name='restrictionsandomissions',
            old_name='self',
            new_name='self_fk',
        ),
        migrations.AddField(
            model_name='feature',
            name='plan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
