# Generated by Django 2.1.3 on 2019-03-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0035_feature_order_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionsandomissions',
            name='feature_type',
            field=models.CharField(default='Disclaimers & Restrictions', max_length=50),
        ),
    ]
