# Generated by Django 2.1.3 on 2019-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0036_auto_20190305_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictionsandomissions',
            name='feature_type',
            field=models.CharField(default='Disclaimers & Restrictions', editable=False, max_length=50),
        ),
    ]
