# Generated by Django 2.1.3 on 2019-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0037_auto_20190305_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['plan', 'order_serial', 'plan_number']},
        ),
        migrations.AlterField(
            model_name='feature',
            name='plan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
