# Generated by Django 2.1.3 on 2019-03-07 10:22

from django.db import migrations, models
import quotes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0038_auto_20190307_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitsandcoverage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quotes.utils.get_img_path_by_filename, verbose_name='Image File'),
        ),
    ]
