# Generated by Django 2.1.3 on 2019-04-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0039_auto_20190307_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmenroll',
            name='form_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
