# Generated by Django 2.1.3 on 2019-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0040_stmenroll_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmenroll',
            name='form_initialized',
            field=models.BooleanField(default=False),
        ),
    ]
