# Generated by Django 2.1.3 on 2019-04-08 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0041_stmenroll_form_initialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='duration_coverages_in_states',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
